---
  - name: Add user to Postgres database
    hosts: all
    gather_facts: false

    tasks:
      - name: fetch rds info
        rds_instance_info:
          db_instance_identifier: "{{ db_instance_identifier }}"
        register:
          rds_instance

      - name: set rds endpoint
        set_fact:
          db_host: "{{ item.address }}"
          db_port: "{{ item.port }}"
        loop: "{{ rds_instance.instances|map(attribute='endpoint')|list }}"

      - name: assert that rds instance can be found using incoming identifier
        assert:
          that:
            - db_host is defined
          fail_msg: "RDS instance {{ db_instance_identifier }} not found."
          quiet: true
      
      - name: check if user already exists
        postgresql_query:
          login_host: "{{ db_host }}"
          login_port: "{{ db_port|default(5432) }}"
          login_db: "postgres"
          login_user: "{{ db_admin_user }}"
          login_password: "{{ db_admin_password }}"
          query: |
            select * from pg_user
            where usename = '{{ new_db_user }}'
        register: db_query_result

      - name: assert that new username does not exist in db
        assert:
          that:
            - db_query_result.rowcount == 0
          fail_msg: "User {{ new_db_user }} already exists in {{ db_instance_identifier }}"
          quiet: true

      # - name: Add user
      #   postgresql_user:
      #     login_host: "{{ db_host }}"
      #     login_port: "{{ db_port }}"
      #     login_user: "{{ db_admin_user }}"
      #     login_password: "{{ db_admin_password }}"
      #     name: "{{ new_db_user }}"
      #     password: "{{ new_db_user_password }}"
