---
  - name: Add user to Postgres database
    hosts: all
    gather_facts: false

    tasks:
      - name: fetch rds info
        rds_instance_info:
          db_instance_identifier: "{{ db_instance_identifier }}"
        register:
          rds_instance

      - debug:
          var: rds_instance.instances

      - name: set rds endpoint
        set_fact:
          db_host: "{{ item.address }}"
          db_port: "{{ item.port }}"
        loop: "{{ rds_instance.instances|map(attribute='endpoint')|list }}"

      - assert:
          that:
            - db_host is defined
      
      - name: check if user already exists
        postgresql_query:
          login_host: "{{ db_host }}"
          login_port: "{{ db_port|default(5432) }}"
          login_db: "postgres"
          login_user: "{{ db_admin_user }}"
          login_password: "{{ db_admin_password }}"
          query: |
            select * from pg_user
            where usename = "{{ new_db_user }}"
        register: db_query_result

      - debug:
          var: db_query_result

      # - name: Add user
      #   postgresql_user:
      #     login_host: "{{ db_host }}"
      #     login_port: "{{ db_port }}"
      #     login_user: "{{ db_admin_user }}"
      #     login_password: "{{ db_admin_password }}"
      #     name: "{{ new_db_user }}"
      #     password: "{{ new_db_user_password }}"
