---
  - name: Add user to Postgres database
    hosts: all
    gather_facts: false

    tasks:
      - name: fetch rds info
        rds_instance_info:
          db_instance_identifier: "{{ db_instance_identifier }}"
        register:
          rds_instance

      - name: set rds endpoint
        set_fact:
          db_host: "{{ item.address }}"
          db_port: "{{ item.port }}"
        loop: "{{ rds_instance.instances|map(attribute='endpoint')|list }}"

      - debug:
          var: db_host

      - debug:
          var: db_port

      - name: check if user already exists
        postgresql_query:
          login_host: "{{ db_host }}"
          login_port: "{{ db_port }}"
          login_user: "{{ db_admin_user }}"
          login_password: "{{ db_admin_password }}"
          query: |
            select * from pg_users

      - name: Add user
        postgresql_user:
          login_host: "{{ db_host }}"
          login_port: "{{ db_port }}"
          login_user: "{{ db_admin_user }}"
          login_password: "{{ db_admin_password }}"
          name: "{{ new_db_user }}"
          password: "{{ new_db_user_password }}"
