---
  - name: Reset password
    hosts: all
    gather_facts: True

    tasks:
      - name: Check password
        assert:
          that:
            - ad_password | default('x') == ad_password_2 | default('y')
          fail_msg: Invalid or empty password
          quiet: yes

      - name: Set new password for existing AD user
        win_domain_user:
          name: "{{ ad_username }}"
          state: present
          password: "{{ ad_password }}"