---
  - name: Add user to Active Directory
    hosts: all
    gather_facts: True

    tasks:
      - win_domain_user:
          name: "{{ full_name | default((firstname + surname) | lower) }}"
          firstname: "{{ firstname }}"
          surname: "{{ surname }}"
          email: "{{ email | default(omit) }}"
          password: "{{ password }}"
          groups:
            - Domain Users