---
  - name: Add user to Active Directory
    hosts: all
    gather_facts: True

    tasks:
      - windows_domain_user:
          name: johndoe
          firstname: John
          surname: Doe
          email: johndoe@extern.innogy.com
          password: Welkom01
          groups:
            - Domain Users