---
  - name: Add user to Active Directory
    hosts: all
    gather_facts: True

    vars:
      group_domain_name: "resources.bda.innogy.com"

    tasks:
      - set_fact:
          account_name: "{{ full_name | default((firstname + surname) | replace(' ','') | lower) }}"

      - win_domain_user:
          name: "{{ account_name }}"
          firstname: "{{ firstname }}"
          surname: "{{ surname }}"
          upn: "{{ account_name }}@{{ group_domain_name }}"
          email: "{{ email | default(omit) }}"
          password: "{{ password }}"
          password_never_expires: "{{ password_never_expires|default('yes')|bool }}"
          enabled: "{{ enable_user|default('yes')|bool }}"
          groups:
            - Domain Users