---
  - name: Install latest security updates.
    hosts: all
    become: True
    gather_facts: False

    tasks:
      - name: list security updates
        yum:
          list: security
        register: result

      - debug:
          var: result

      - name: install security updates
        yum:
          name: '*'
          security: yes
          state: latest