---
  - name: Cleanup /tmp directory (inside docker containers)
    hosts: all
    gather_facts: True

    tasks:
      - debug:
          var: ansible_python_version

      - name: get docker containers
        docker_host_info:
          containers: yes
        register: result

      - name: show output
        debug:
          var: result.host_info
