---
  - name: Cleanup /tmp directory (inside docker containers)
    hosts: all
    become: True
    gather_facts: True

    tasks:
      - name: fix python2 -> python3 (if necessary)
        block:
          - name: install python3
            yum:
              name:
                - python36
                - python36-devel
                - python36-pip
              state: present

          - name: set Python interpreter
            set_fact:
              ansible_python_interpreter: "/usr/bin/python3"
        when: ansible_python_version | version('3', '<')

      - name: get docker containers
        docker_host_info:
          containers: yes
        register: result

      - name: show output
        debug:
          var: result.host_info
