---
  - name: Cleanup /tmp directory (inside docker containers)
    hosts: all
    become: True
    gather_facts: True

    vars:
      rapidminer:
        agent_container: rapidminer-agent

    tasks:
      - name: fix python2 -> python3 (if necessary)
        block:
          - name: install python3
            yum:
              name:
                - python36
                - python36-devel
                - python36-tools
              state: present

          - name: set Python interpreter
            set_fact:
              ansible_python_interpreter: "/usr/bin/python3"
        when: ansible_python_version is version('3', '<')

      - debug:
          msg: "Using Python version {{ ansible_python_interpreter }}"

      - name: install pip packages
        pip:
          name:
            - docker
          executable: pip-3.6

      - name: get docker containers
        docker_host_info:
          containers: yes
          containers_filters:
            label: "com.amazonaws.ecs.container-name={{ rapidminer.agent_container }}"
        register: result

      - name: expecting only 1 (one) container exists
        assert:
          that:
            - result.containers | length == 1
          fail_msg: "Expecting only 1 (one) {{ rapidminer.agent_container }} container."

      - set_fact:
          container_id: "{{ result.containers.0.Id }}"
          container_name: "{{ result.containers.0.Names.0 | regex_replace('^\\/', '')}}"

      - debug:
          var: container_name

      - name: cleanup /tmp directory _inside_ docker container
        docker_exec:
          name: "{{ container_name }}"
          command: bash -c '/usr/bin/find /tmp/wsdl* -type f -atime +1 -exec rm -f {} \; 2>/dev/null'
        register: out

      - debug:
          var: out


