---
  - name: Install package
    hosts: all
    gather_facts: True

    tasks:
      - name: Distribution
        debug: 
          var: ansible_distribution

      - name: Distribution version
        debug: 
          var: ansible_distribution_version

      - name: Distribution major version
        debug: 
          var: ansible_distribution_major_version