---
  - name: Cloning private Gitlab repository
    hosts: all

    tasks:
      - block:
        - name: Create temporary directory
          tempfile:
            state: directory
            suffix: ".gitlab"
          register: tmpdir

        - debug:
            msg: ">> cloning to directory '{{tmpdir.path}}' "

        - name: Clone Gitlab repository {{ gitlab_repo }}
          git:
            repo: "https://{{ gitlab_user | urlencode }}:{{ gitlab_pwd | urlencode }}@{{ gitlab_repo }}"
            dest: "{{ tmpdir.path }}"

        always:

          - name: Delete temporary directory
            file:
              path: "{{ tmpdir.path }}"
              state: absent
            when: tmpdir.path is defined
