---
  - name: Cloning private Gitlab repository
    hosts: all

    tasks:
      - block:
        - name: Create temporary directory
          tempfile:
            state: directory
            suffix: ".gitlab"
          register: tmpdir

        - debug:
            msg: ">> cloning to directory '{{tmpdir.path}}' "

        - name: Ping execute
          shell: "ping -c 1 -q -W 1 gitlab.bda.innogy.com"
          register: command_output
          ignore_errors: yes
          no_log: true
          changed_when: false

        - name: Ping report
          debug: 
            msg: "{{ command_output.results }}"

        - name: Clone Gitlab repository {{ gitlab_repo }}
          git:
            repo: "https://{{ gitlab_user | urlencode }}:{{ gitlab_pwd | urlencode }}@{{ gitlab_repo }}"
            dest: "{{ tmpdir.path }}"

        always:

          - name: Delete temporary directory
            file:
              path: "{{ tmpdir.path }}"
              state: absent
            when: tmpdir.path is defined
